#!/bin/sh

# this makes all assets for the game

echo "Sorry - make_all does nothing these days. Sucks, doesn't it?"

# using $@ in quotes to stop params with spaces in them being split by shell
# resconvert "$@" resfiles/make_all.res
